-- : Identify films that have never been rented out. Use a combination of CTE and LEFT JOIN for this task.
WITH CTE_NOT_RENTED AS
	(SELECT DISTINCT SE_I.FILM_ID
		FROM INVENTORY AS SE_I
		LEFT JOIN RENTAL AS SE_R ON SE_I.INVENTORY_ID = SE_R.INVENTORY_ID
		WHERE SE_R.INVENTORY_ID IS NULL )
SELECT SE_F.FILM_ID,
	SE_F.TITLE
FROM FILM AS SE_F
LEFT JOIN CTE_ALL_RENTALS AS CTE ON SE_F.FILM_ID = CTE.FILM_ID
WHERE CTE.FILM_ID IS NOT NULL;

-- IT CAN BE SOLVED  WITH INNER JOIN INSTED OF LEFT  AND FILTERING  by NOT NUL ,BUT REQUIRMENT IS TO USE LEFT JOIN