SELECT DISTINCT C.FIRST_NAME,
	C.LAST_NAME,
	C.EMAIL
FROM CUSTOMER C
INNER JOIN RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
INNER JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
INNER JOIN FILM F ON I.FILM_ID = F.FILM_ID
INNER JOIN FILM_ACTOR FA ON F.FILM_ID = FA.FILM_ID
INNER JOIN ACTOR A ON FA.ACTOR_ID = A.ACTOR_ID
WHERE A.FIRST_NAME = 'Nick'
	AND A.LAST_NAME = 'Wahlberg';