-- (INNER JOIN): Find the names of customers who rented films with a replacement cost greater than $20 and which belong to the 'Action' or 'Comedy' categories.

SELECT DISTINCT(SE_C.FIRST_NAME)
FROM CUSTOMER AS SE_C
INNER JOIN RENTAL AS SE_R ON SE_C.CUSTOMER_ID = SE_R.CUSTOMER_ID
INNER JOIN INVENTORY AS SE_I ON SE_R.INVENTORY_ID = SE_I.INVENTORY_ID
INNER JOIN FILM AS SE_F ON SE_I.FILM_ID = SE_F.FILM_ID
INNER JOIN FILM_CATEGORY AS SE_FC ON SE_FC.FILM_ID = SE_F.FILM_ID
INNER JOIN CATEGORY AS SE_CA ON SE_CA.CATEGORY_ID = SE_FC.CATEGORY_ID
WHERE SE_F.REPLACEMENT_COST > 20
	AND SE_CA.NAME IN ('Action','Comedy')